// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1eGpktblIAOrI68tgPxCq9Fsa1xdSXI',
    appId: '1:759556546667:web:9cd21fba85ac5d29e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    authDomain: 'while-2.firebaseapp.com',
    storageBucket: 'while-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUsLcgtaEnKKzXNYMhpzP7zkVZFmh_rk',
    appId: '1:759556546667:android:cf2a8c2620d5569fe3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    storageBucket: 'while-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Hxumu0O4bCtvK-GHr8h_FVL8svb9eag',
    appId: '1:759556546667:ios:1537b221e787ac7ce3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    storageBucket: 'while-2.appspot.com',
    iosClientId: '759556546667-djfl883co81974tku1faaouceph35f4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.whileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Hxumu0O4bCtvK-GHr8h_FVL8svb9eag',
    appId: '1:759556546667:ios:d7e0865e62aec935e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    storageBucket: 'while-2.appspot.com',
    iosClientId: '759556546667-8khagoe9n7ho2qh7dh0af4v25qgl88r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.whileApp.RunnerTests',
  );
}
